---
# Source: ambassador/templates/crds-rbac.yaml

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ambassador-crds
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-5.1.0
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/managed-by: Tiller
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources:
    - customresourcedefinitions
    resourceNames:
    - authservices.getambassador.io
    - mappings.getambassador.io
    - modules.getambassador.io
    - ratelimitservices.getambassador.io
    - tcpmappings.getambassador.io
    - tlscontexts.getambassador.io
    - tracingservices.getambassador.io
    - kubernetesendpointresolvers.getambassador.io
    - kubernetesserviceresolvers.getambassador.io
    - consulresolvers.getambassador.io
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ambassador-crds
  labels:
    app.kubernetes.io/name: ambassador
    helm.sh/chart: ambassador-5.1.0
    app.kubernetes.io/instance: ambassador
    app.kubernetes.io/managed-by: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ambassador-crds
subjects:
  - name: ambassador
    namespace: "default"
    kind: ServiceAccount
