---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbinv2
  labels:
    app: httpbinv2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbinv2
  template:
    metadata:
      labels:
        app: httpbinv2
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbinv2
spec:
  ports:
  - port: 80
  selector:
    app: httpbinv2
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: httpbin-canary
spec:
  prefix: /httpbin/
  service: httpbinv2:80
  add_response_headers:
    # https://github.com/datawire/ambassador/issues/1665
    x-api-version: "v2"
  weight: 10