---
# terminate tls at gateway
apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: tls
spec:
  hosts: ["*"]
  secret: gateway-tls-keys
  redirect_cleartext_from: 8080
---
apiVersion: getambassador.io/v1
kind: TLSContext
metadata:
  name: upstream-api
spec:
  alpn_protocols: h2
  secret: upstream-api-tls-keys